"""add referencia + unique + indexes

Revision ID: 7dc8aa8469d0
Revises: 
Create Date: 2025-08-19 14:52:20.032249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7dc8aa8469d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movimientos_puntos_id', table_name='movimientos_puntos')
    op.drop_table('movimientos_puntos')
    op.drop_index('codigo_sap', table_name='clientes')
    op.drop_index('ix_clientes_correo', table_name='clientes')
    op.drop_index('ix_clientes_id_cliente', table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id_cliente', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('correo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('telefono', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('codigo_sap', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('fecha_registro', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_clientes_id_cliente', 'clientes', ['id_cliente'], unique=False)
    op.create_index('ix_clientes_correo', 'clientes', ['correo'], unique=True)
    op.create_index('codigo_sap', 'clientes', ['codigo_sap'], unique=True)
    op.create_table('movimientos_puntos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('puntos', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('fecha', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('referencia', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_vencimiento', sa.DATE(), nullable=True),
    sa.Column('descripcion', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name='movimientos_puntos_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_movimientos_puntos_id', 'movimientos_puntos', ['id'], unique=False)
    # ### end Alembic commands ###
